---
title: "Restarting covidseir fits"
output: rmarkdown::pdf_document
vignette: >
  %\VignetteIndexEntry{Dividing a time series into multiple fits}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.asp = 0.62,
  fig.width = 5
)
```

```{r setup, message=FALSE, warning=FALSE}
library(covidseir)
library(dplyr)
library(ggplot2)
ymd <- lubridate::ymd
options(future.rng.onMisuse='ignore')
```

# Data

First, we will read in the British Columbia, Canada COVID-19 reported-case data. This comes from <http://www.bccdc.ca/Health-Info-Site/Documents/BCCDC_COVID19_Dashboard_Case_Details.csv>.

```{r dat}
dat <- structure(list(value = c(1, 1, 4, 6, 4, 6, 1, 3, 5, 11, 20, 12, 
25, 12, 27, 46, 41, 60, 47, 62, 46, 43, 88, 59, 91, 62, 62, 37, 
30, 82, 56, 47, 55, 31, 21, 13, 51, 40, 33, 34, 41, 28, 15, 30, 
44, 14, 51, 25, 30, 15, 34, 63, 33, 37, 72, 61, 15, 58, 41, 26, 
29, 23, 33, 21, 16, 24, 29, 21, 14, 8, 17, 10, 13, 16, 14, 21, 
8, 11, 5, 19, 11, 22, 12, 4, 9, 8, 7, 10, 5, 11, 9, 16, 4, 23, 
2, 4, 12, 7, 9, 10, 14, 12, 17, 14, 14, 9, 11, 19, 9, 5, 9, 6, 
17, 11, 12, 21, 12, 9, 13, 3, 12, 17, 10, 9, 12, 16, 7, 10, 19, 
18, 22, 25, 23, 20, 13, 19, 24, 33, 44, 19, 29, 33, 34, 32, 30, 
30, 21, 21, 24, 47, 26, 39, 52, 29, 48, 28, 43, 46, 47, 51, 38, 
42, 46, 86, 73, 90, 100, 86, 51, 77, 65, 84, 90, 115, 79, 81), 
    day = 1:176), row.names = c(NA, -176L), 
  class = "data.frame")
dat <- dplyr::as_tibble(dat)
dat$date <- ymd("2020-03-01") + dat$day - 1
```

```{r plot-raw-dat}
ggplot(dat, aes(date, value)) + geom_line()
```

```{r f-seg}
samp_frac <- c(rep(0.14, 13), rep(0.21, 38))
samp_frac <- c(samp_frac, rep(0.37, nrow(dat) - length(samp_frac)))
f_seg <- c(0, rep(1, nrow(dat) - 1))
day_new_f <- which(dat$date == ymd("2020-05-01"))
f_seg[seq(day_new_f, length(f_seg))] <- 2
day_ch <- which(dat$date == ymd("2020-06-01"))
f_seg[seq(day_ch, length(f_seg))] <- 3
f_seg
```

```{r}
dat1 <- filter(dat, date < ymd("2020-06-01"))
dat2 <- filter(dat, date >= ymd("2020-06-01"))

samp_frac1 <- samp_frac[seq_len(nrow(dat1))]
samp_frac2 <- samp_frac[seq(nrow(dat1) + 1, length(samp_frac))]

f_seg1 <- f_seg[seq_len(nrow(dat1))]
f_seg2 <- f_seg[seq(nrow(dat1) + 1, length(f_seg))]
```

```{r fit1, warning=FALSE}
fit0 <- covidseir::fit_seir(
  daily_cases = dat$value,
  samp_frac_fixed = samp_frac, 
  f_seg = f_seg,
  i0_prior = c(log(8), 1),
  e_prior = c(0.8, 0.05),
  start_decline_prior = c(log(15), 0.1),
  end_decline_prior = c(log(22), 0.1),
  f_prior = cbind(c(0.4, 0.5, 0.6), c(0.2, 0.2, 0.2)),
  R0_prior = c(log(2.6), 0.2),
  days_back = 30,
  N_pop = 5.1e6, # BC population
  iter = 500, # number of posterior samples
  fit_type = "optimizing" # for speed only
)

fit1 <- covidseir::fit_seir(
  daily_cases = dat1$value,
  samp_frac_fixed = samp_frac1, 
  f_seg = f_seg1,
  i0_prior = c(log(8), 1),
  e_prior = c(0.8, 0.05),
  start_decline_prior = c(log(15), 0.1),
  end_decline_prior = c(log(22), 0.1),
  f_prior = cbind(c(0.4, 0.5), c(0.2, 0.2)),
  R0_prior = c(log(2.6), 0.2),
  days_back = 30,
  N_pop = 5.1e6, # BC population
  iter = 500, # number of posterior samples
  fit_type = "optimizing" # for speed only
)
proj <- covidseir::project_seir(fit1, iter = 1:100)
tidy_proj <- covidseir::tidy_seir(proj, resample_y_rep = 50)

first_day <- min(dat$date)
last_day <- 300 # how many days to create dates for
lut <- dplyr::tibble(
  day = seq_len(last_day),
  date = seq(first_day, first_day + length(day) - 1, by = "1 day")
)
tidy_proj <- dplyr::left_join(tidy_proj, lut, by = "day")

covidseir::plot_projection(tidy_proj, obs_dat = dat,
  value_column = "value", date_column = "date")

p <- fit1$post
R0 <- p$R0
hist(R0)
R0_hat <- unname(MASS::fitdistr(R0, "lognormal")$estimate)
hist(R0, probability = TRUE, main = "")
x <- seq(2, 5, length.out = 200)
lines(x, dlnorm(x, R0_hat[1], R0_hat[2]), type = "l")

proj1 <- covidseir::project_seir(fit1, iter = 1:100, return_states = TRUE)
i30 <- filter(proj1, variable %in% c("I", "Id", "E1", "E2", "E1d", "E2d") & time == max(proj1$time) - 30) %>% 
  group_by(.iteration) %>% 
  summarise(value = sum(value), .groups = "drop") %>% 
  pull(value)
hist(i30, breaks = 40)
i30_hat <- unname(MASS::fitdistr(i30, "lognormal")$estimate)

hist(p$e)
e_hat <- c(mean(p$e), sd(p$e))

start_decline_fake <- c(log(1), 0.1)
end_decline_fake <- c(log(1), 0.1)
x <- seq(0, 8, length.out = 500)
plot(x, dlnorm(x, start_decline_fake[1], start_decline_fake[2]), type = "l")
lines(x, dlnorm(x, end_decline_fake[1], end_decline_fake[2]), type = "l")

# state_0 <- c(E1_frac = 0.4, E2_frac = 0.1, I_frac = 0.5, Q_num = 0, R_num = 0,
#     E1d_frac = 0.4, E2d_frac = 0.1, Id_frac = 0.5, Qd_num = 0, Rd_num = 0)

# state0 at time -30
S0 <- proj1 %>% filter(time == max(time) - 30) %>%
  group_by(variable) %>% 
  summarise(value = mean(value), .groups = "drop")
state_order <- c("S", "E1", "E2", "I", "Q", "R", "Sd", "E1d", "E2d", "Id", "Qd", "Rd")
S0_hat <- S0$value
names(S0_hat) <- S0$variable
S0_hat <- S0_hat[state_order]
S0_hat

# i0 <- S0_hat[['I']] + S0_hat[['Id']]
i0 <- exp(i30_hat[[1]])
state_0 <- c(
  E1_frac = S0_hat[['E1']] / ((1 - e_hat[1]) * i0), 
  E2_frac = S0_hat[['E2']] / ((1 - e_hat[1]) * i0), 
  I_frac = S0_hat[['I']] / ((1 - e_hat[1]) * i0), 
  Q_num = S0_hat[['Q']], 
  R_num = S0_hat[['R']],
  E1d_frac = S0_hat[['E1d']] / (e_hat[1] * i0), 
  E2d_frac = S0_hat[['E2d']] / (e_hat[1] * i0), 
  Id_frac = S0_hat[['Id']] / (e_hat[1] * i0), 
  Qd_num = S0_hat[['Qd']], 
  Rd_num = S0_hat[['Rd']])

# y0[1] = nsi * (N_pop - i0); // S = nsi * (pars[["N"]] - i0)
# y0[2] = y0_vars[1] * nsi * i0; // E1 = E1_frac * nsi * i0
# y0[3] = y0_vars[2] * nsi * i0; // E2 = E2_frac * nsi * i0
# y0[4] = y0_vars[3] * nsi * i0; // I = I_frac * nsi * i0
# y0[5] = y0_vars[4]; // Q = Q_num
# y0[6] = y0_vars[5]; // R = R_num
# y0[7] = fsi * (N_pop - i0); // Sd = fsi * (pars[["N"]] - i0)
# y0[8] = y0_vars[6] * fsi * i0; // E1d = E1d_frac * fsi * i0
# y0[9] = y0_vars[7] * fsi * i0; // E2d = E2d_frac * fsi * i0
# y0[10] = y0_vars[8] * fsi * i0; // Id = Id_frac * fsi * i0
# y0[11] = y0_vars[9]; // Qd = Qd_num
# y0[12] = y0_vars[10]; // Rd = Rd_num

plot(dat2$value, type = "o")

f_seg2 <- rep(1, length(f_seg2))
f_seg2[1] <- 0

f <- p$f_s[,ncol(p$f_s)]
hist(f)
f_hat <- c(mean(f), sd(f))

hist(p$phi[,1])
phi_hat <- unname(MASS::fitdistr(p$phi, "lognormal")$estimate)

fit2 <- covidseir::fit_seir(
  daily_cases = dat2$value,
  samp_frac_fixed = samp_frac2, 
  f_seg = f_seg2,
  i0_prior = c(i30_hat[1], i30_hat[2]),
  e_prior = c(e_hat[1], e_hat[2]),
  days_back = 30,
  start_decline_prior = start_decline_fake,
  end_decline_prior = end_decline_fake,
  state_0 = state_0,
  pars = c(D = 5, k1 = 1/5, k2 = 1, q = 0.05, ud = 0.1, ur = 0.02, f0 = f_hat[1]),
  f_prior = cbind(c(0.6), c(0.2)),
  R0_prior = c(R0_hat[1], R0_hat[2]),
  use_ramp = FALSE,
  N_pop = 5.1e6, # BC population
  iter = 500, # number of posterior samples
  fit_type = "optimizing", # for speed only
  algorithm = "BFGS",
  phi_prior = phi_hat
)

proj2 <- covidseir::project_seir(fit2, iter = 1:100)
tidy_proj2 <- covidseir::tidy_seir(proj2, resample_y_rep = 50)
first_day2 <- min(dat2$date)
lut2 <- dplyr::tibble(
  day = seq_len(last_day),
  date = seq(first_day2, first_day2 + length(day) - 1, by = "1 day")
)
tidy_proj2 <- dplyr::left_join(tidy_proj2, lut2, by = "day")

# covidseir::plot_projection(tidy_proj2, obs_dat = dat2,
#   value_column = "value", date_column = "date")

g1 <- tidy_proj %>% bind_rows(tidy_proj2) %>% 
  covidseir::plot_projection(obs_dat = dat,
  value_column = "value", date_column = "date") +
  geom_vline(xintercept = ymd("2020-06-01"), lty = 2) +
  theme_light() +
  theme(axis.title.x = element_blank()) +
  coord_cartesian(ylim = c(0, 150), expand = FALSE)
  # scale_y_log10()

proj0 <- covidseir::project_seir(fit0, iter = 1:100)
tidy_proj0 <- covidseir::tidy_seir(proj0, resample_y_rep = 50)
tidy_proj0 <- dplyr::left_join(tidy_proj0, lut, by = "day")

fit0
fit1
fit2

g2 <- tidy_proj0 %>%
  covidseir::plot_projection(obs_dat = dat,
  value_column = "value", date_column = "date") +
  theme_light() +
  theme(axis.title.x = element_blank()) +
  coord_cartesian(ylim = c(0, 150), expand = FALSE)

cowplot::plot_grid(g1, g2, ncol = 1)
```
